///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace react_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenBrowser recording.
    /// </summary>
    [TestModule("4183e39e-b002-4cc1-9e00-cfa900c3477e", ModuleType.Recording, 1)]
    public partial class OpenBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the react_demoRepository repository.
        /// </summary>
        public static react_demoRepository repo = react_demoRepository.Instance;

        static OpenBrowser instance = new OpenBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenBrowser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenBrowser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://localhost:3000' with browser 'Chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://localhost:3000", "Chrome", "", false, false, false, false, false, false, false, true);
            Delay.Milliseconds(7900);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewTabProfile1MicrosoftEdge.Root1.InputArea' at 106;33.", repo.NewTabProfile1MicrosoftEdge.Root1.InputAreaInfo, new RecordItemIndex(1));
            repo.NewTabProfile1MicrosoftEdge.Root1.InputArea.Click("106;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'validate' with focus on 'NewTabProfile1MicrosoftEdge.Root1.InputArea'.", repo.NewTabProfile1MicrosoftEdge.Root1.InputAreaInfo, new RecordItemIndex(2));
            repo.NewTabProfile1MicrosoftEdge.Root1.InputArea.PressKeys("validate");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewTabProfile1MicrosoftEdge.Root1.Submit' at 144;15.", repo.NewTabProfile1MicrosoftEdge.Root1.SubmitInfo, new RecordItemIndex(3));
            repo.NewTabProfile1MicrosoftEdge.Root1.Submit.Click("144;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='validate') on item 'NewTabProfile1MicrosoftEdge.Root1.Validate'.", repo.NewTabProfile1MicrosoftEdge.Root1.ValidateInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.NewTabProfile1MicrosoftEdge.Root1.ValidateInfo, "Text", "validate");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
