///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace react_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PerfromAction recording.
    /// </summary>
    [TestModule("a53a9939-8874-4033-9ec7-6718fd748211", ModuleType.Recording, 1)]
    public partial class PerfromAction : ITestModule
    {
        /// <summary>
        /// Holds an instance of the react_demoRepository repository.
        /// </summary>
        public static react_demoRepository repo = react_demoRepository.Instance;

        static PerfromAction instance = new PerfromAction();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PerfromAction()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PerfromAction Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ReactAppAnd1MorePageProfile1.Root2.Root1' at 614;150.", repo.ReactAppAnd1MorePageProfile1.Root2.Root1Info, new RecordItemIndex(0));
            repo.ReactAppAnd1MorePageProfile1.Root2.Root1.Click("614;150");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ReactApp.Container.SubContainer' at 240;281.", repo.ReactApp.Container.SubContainerInfo, new RecordItemIndex(1));
            repo.ReactApp.Container.SubContainer.Click("240;281");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'entering text for validation' with focus on 'ReactApp'.", repo.ReactApp.SelfInfo, new RecordItemIndex(2));
            repo.ReactApp.Self.EnsureVisible();
            Keyboard.Press("entering text for validation");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ReactApp.Container.Submit' at 232;21.", repo.ReactApp.Container.SubmitInfo, new RecordItemIndex(3));
            repo.ReactApp.Container.Submit.Click("232;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ReactApp.Container.EnteringTextForValidation'.", repo.ReactApp.Container.EnteringTextForValidationInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ReactApp.Container.EnteringTextForValidationInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='entering text for validation') on item 'ReactApp.Container.EnteringTextForValidation'.", repo.ReactApp.Container.EnteringTextForValidationInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ReactApp.Container.EnteringTextForValidationInfo, "InnerText", "entering text for validation");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
