///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace react_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the react_demoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d44b7d9f-63be-4933-9739-19adccdfabd8")]
    public partial class react_demoRepository : RepoGenBaseFolder
    {
        static react_demoRepository instance = new react_demoRepository();
        react_demoRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        react_demoRepositoryFolders.TestAutomationForGUITestingRanoreAppFolder _testautomationforguitestingranore;
        react_demoRepositoryFolders.ExplorerAppFolder _explorer;
        react_demoRepositoryFolders.NewTabProfile1MicrosoftEdgeAppFolder _newtabprofile1microsoftedge;
        react_demoRepositoryFolders.Explorer1AppFolder _explorer1;
        react_demoRepositoryFolders.ReactAppAnd1MorePageProfile1AppFolder _reactappand1morepageprofile1;
        react_demoRepositoryFolders.ReactAppAppFolder _reactapp;

        /// <summary>
        /// Gets the singleton class instance representing the react_demoRepository element repository.
        /// </summary>
        [RepositoryFolder("d44b7d9f-63be-4933-9739-19adccdfabd8")]
        public static react_demoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public react_demoRepository() 
            : base("react_demoRepository", "/", null, 0, false, "d44b7d9f-63be-4933-9739-19adccdfabd8", ".\\RepositoryImages\\react_demoRepositoryd44b7d9f.rximgres")
        {
            _applicationundertest = new react_demoRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _testautomationforguitestingranore = new react_demoRepositoryFolders.TestAutomationForGUITestingRanoreAppFolder(this);
            _explorer = new react_demoRepositoryFolders.ExplorerAppFolder(this);
            _newtabprofile1microsoftedge = new react_demoRepositoryFolders.NewTabProfile1MicrosoftEdgeAppFolder(this);
            _explorer1 = new react_demoRepositoryFolders.Explorer1AppFolder(this);
            _reactappand1morepageprofile1 = new react_demoRepositoryFolders.ReactAppAnd1MorePageProfile1AppFolder(this);
            _reactapp = new react_demoRepositoryFolders.ReactAppAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d44b7d9f-63be-4933-9739-19adccdfabd8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("ac3e3aa1-d828-4719-a490-5ec3fd9a759d")]
        public virtual react_demoRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The TestAutomationForGUITestingRanore folder.
        /// </summary>
        [RepositoryFolder("8ccf4365-a576-4d4b-b4d8-eb44c815b391")]
        public virtual react_demoRepositoryFolders.TestAutomationForGUITestingRanoreAppFolder TestAutomationForGUITestingRanore
        {
            get { return _testautomationforguitestingranore; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("122b9660-6474-483d-9c38-5b3fdc0f7ca9")]
        public virtual react_demoRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The NewTabProfile1MicrosoftEdge folder.
        /// </summary>
        [RepositoryFolder("87fa683f-4620-46d2-9ad4-02a3b6457994")]
        public virtual react_demoRepositoryFolders.NewTabProfile1MicrosoftEdgeAppFolder NewTabProfile1MicrosoftEdge
        {
            get { return _newtabprofile1microsoftedge; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("c3cc2416-b6ec-4a0f-8cda-9171a52962fb")]
        public virtual react_demoRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The ReactAppAnd1MorePageProfile1 folder.
        /// </summary>
        [RepositoryFolder("712b75b7-9147-44f8-9848-ba634993efa5")]
        public virtual react_demoRepositoryFolders.ReactAppAnd1MorePageProfile1AppFolder ReactAppAnd1MorePageProfile1
        {
            get { return _reactappand1morepageprofile1; }
        }

        /// <summary>
        /// The ReactApp folder.
        /// </summary>
        [RepositoryFolder("b542ea33-a686-4ec5-95ec-85115e3453e3")]
        public virtual react_demoRepositoryFolders.ReactAppAppFolder ReactApp
        {
            get { return _reactapp; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class react_demoRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("ac3e3aa1-d828-4719-a490-5ec3fd9a759d")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "ac3e3aa1-d828-4719-a490-5ec3fd9a759d", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ac3e3aa1-d828-4719-a490-5ec3fd9a759d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ac3e3aa1-d828-4719-a490-5ec3fd9a759d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The TestAutomationForGUITestingRanoreAppFolder folder.
        /// </summary>
        [RepositoryFolder("8ccf4365-a576-4d4b-b4d8-eb44c815b391")]
        public partial class TestAutomationForGUITestingRanoreAppFolder : RepoGenBaseFolder
        {
            react_demoRepositoryFolders.Root1Folder _root1;
            react_demoRepositoryFolders.Root2Folder _root2;
            RepoItemInfo _contentsseparatorInfo;
            RepoItemInfo _view1000Info;
            RepoItemInfo _noneInfo;
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new TestAutomationForGUITestingRanore  folder.
            /// </summary>
            public TestAutomationForGUITestingRanoreAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TestAutomationForGUITestingRanore", "/form[@title>'Test Automation for GUI Testing']", parentFolder, 30000, null, true, "8ccf4365-a576-4d4b-b4d8-eb44c815b391", "")
            {
                _root1 = new react_demoRepositoryFolders.Root1Folder(this);
                _root2 = new react_demoRepositoryFolders.Root2Folder(this);
                _contentsseparatorInfo = new RepoItemInfo(this, "ContentsSeparator", "container[@name>'Test Automation for GUI Testing']/container[@name='Microsoft Edge']//container[@classname='ContentsSeparator']", ".//container[@classname='ContentsSeparator']", 30000, null, "8ec5953b-04fc-467a-a4fe-21fea4d2b3dc");
                _view1000Info = new RepoItemInfo(this, "View1000", "container[@name>'Test Automation for GUI Testing']/container[@name='Microsoft Edge']//toolbar[@automationid='view_1000']", ".//toolbar[@automationid='view_1000']", 30000, null, "2b1dd869-1a84-4f67-b4e2-5287febf4c6e");
                _noneInfo = new RepoItemInfo(this, "None", "container[@name>'React App - Microsoft Edg']/container[@name='Microsoft Edge']/?/?/container[@classname='BrowserView']/container[3]//container[@automationid='41681536']/?/?/container[@automationid='root']/text[@orientation='None']", ".//container[@automationid='root']/text[@orientation='None']", 30000, null, "8fff7e63-56d3-4366-a498-13680e7e326b");
                _submitInfo = new RepoItemInfo(this, "Submit", "container[@name>'React App - Microsoft Edg']/container[@name='Microsoft Edge']/?/?/container[@classname='BrowserView']/container[3]//container[@automationid='41681536']/?/?/container[@automationid='root']/button[@name='Submit']", ".//button[@name='Submit']", 30000, null, "2b8a8398-6db9-4f6a-8165-4bae146d8eb9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8ccf4365-a576-4d4b-b4d8-eb44c815b391")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8ccf4365-a576-4d4b-b4d8-eb44c815b391")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContentsSeparator item.
            /// </summary>
            [RepositoryItem("8ec5953b-04fc-467a-a4fe-21fea4d2b3dc")]
            public virtual Ranorex.Container ContentsSeparator
            {
                get
                {
                    return _contentsseparatorInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContentsSeparator item info.
            /// </summary>
            [RepositoryItemInfo("8ec5953b-04fc-467a-a4fe-21fea4d2b3dc")]
            public virtual RepoItemInfo ContentsSeparatorInfo
            {
                get
                {
                    return _contentsseparatorInfo;
                }
            }

            /// <summary>
            /// The View1000 item.
            /// </summary>
            [RepositoryItem("2b1dd869-1a84-4f67-b4e2-5287febf4c6e")]
            public virtual Ranorex.ToolBar View1000
            {
                get
                {
                    return _view1000Info.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The View1000 item info.
            /// </summary>
            [RepositoryItemInfo("2b1dd869-1a84-4f67-b4e2-5287febf4c6e")]
            public virtual RepoItemInfo View1000Info
            {
                get
                {
                    return _view1000Info;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("8fff7e63-56d3-4366-a498-13680e7e326b")]
            public virtual Ranorex.Text None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("8fff7e63-56d3-4366-a498-13680e7e326b")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("2b8a8398-6db9-4f6a-8165-4bae146d8eb9")]
            public virtual Ranorex.Button Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("2b8a8398-6db9-4f6a-8165-4bae146d8eb9")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The Root1 folder.
            /// </summary>
            [RepositoryFolder("6628fb38-7312-429e-96a6-07df427d89d8")]
            public virtual react_demoRepositoryFolders.Root1Folder Root1
            {
                get { return _root1; }
            }

            /// <summary>
            /// The Root2 folder.
            /// </summary>
            [RepositoryFolder("ed766b88-9f08-48c3-ade0-245c79137dc5")]
            public virtual react_demoRepositoryFolders.Root2Folder Root2
            {
                get { return _root2; }
            }
        }

        /// <summary>
        /// The Root1Folder folder.
        /// </summary>
        [RepositoryFolder("6628fb38-7312-429e-96a6-07df427d89d8")]
        public partial class Root1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _rootInfo;
            RepoItemInfo _addingsolutionInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _noneInfo;

            /// <summary>
            /// Creates a new Root1  folder.
            /// </summary>
            public Root1Folder(RepoGenBaseFolder parentFolder) :
                    base("Root1", "container[@name>'React App - Microsoft Edg']/container[@name='Microsoft Edge']/?/?/container[@classname='BrowserView']/container[3]//container[@automationid='61697056']/?/?/container[@automationid='root']", parentFolder, 30000, null, false, "6628fb38-7312-429e-96a6-07df427d89d8", "")
            {
                _rootInfo = new RepoItemInfo(this, "Root", "", "", 30000, null, "cb93dcf1-6233-44f3-8d51-d71528413279");
                _addingsolutionInfo = new RepoItemInfo(this, "AddingSolution", "?/?/text[@name='Adding solution']", "", 30000, null, "f28d12ce-5bca-4c55-99de-c4ce0931f64f");
                _submitInfo = new RepoItemInfo(this, "Submit", "button[@name='Submit']", "", 30000, null, "3baabed4-d4a8-4f4f-bf11-74b63074bc3c");
                _noneInfo = new RepoItemInfo(this, "None", "text[@orientation='None']", "", 30000, null, "611ce3c0-b854-40ee-b1ec-bffcb474a447");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6628fb38-7312-429e-96a6-07df427d89d8")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6628fb38-7312-429e-96a6-07df427d89d8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Root item.
            /// </summary>
            [RepositoryItem("cb93dcf1-6233-44f3-8d51-d71528413279")]
            public virtual Ranorex.Container Root
            {
                get
                {
                    return _rootInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Root item info.
            /// </summary>
            [RepositoryItemInfo("cb93dcf1-6233-44f3-8d51-d71528413279")]
            public virtual RepoItemInfo RootInfo
            {
                get
                {
                    return _rootInfo;
                }
            }

            /// <summary>
            /// The AddingSolution item.
            /// </summary>
            [RepositoryItem("f28d12ce-5bca-4c55-99de-c4ce0931f64f")]
            public virtual Ranorex.Text AddingSolution
            {
                get
                {
                    return _addingsolutionInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AddingSolution item info.
            /// </summary>
            [RepositoryItemInfo("f28d12ce-5bca-4c55-99de-c4ce0931f64f")]
            public virtual RepoItemInfo AddingSolutionInfo
            {
                get
                {
                    return _addingsolutionInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("3baabed4-d4a8-4f4f-bf11-74b63074bc3c")]
            public virtual Ranorex.Button Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("3baabed4-d4a8-4f4f-bf11-74b63074bc3c")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("611ce3c0-b854-40ee-b1ec-bffcb474a447")]
            public virtual Ranorex.Text None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("611ce3c0-b854-40ee-b1ec-bffcb474a447")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }
        }

        /// <summary>
        /// The Root2Folder folder.
        /// </summary>
        [RepositoryFolder("ed766b88-9f08-48c3-ade0-245c79137dc5")]
        public partial class Root2Folder : RepoGenBaseFolder
        {
            RepoItemInfo _rootInfo;
            RepoItemInfo _validatethistextInfo;
            RepoItemInfo _submit1Info;
            RepoItemInfo _none1Info;

            /// <summary>
            /// Creates a new Root2  folder.
            /// </summary>
            public Root2Folder(RepoGenBaseFolder parentFolder) :
                    base("Root2", "container[@name>'React App - Microsoft Edg']/container[@name='Microsoft Edge']/?/?/container[@classname='BrowserView']/container[3]//container[@automationid='27106816']/?/?/container[@automationid='root']", parentFolder, 30000, null, false, "ed766b88-9f08-48c3-ade0-245c79137dc5", "")
            {
                _rootInfo = new RepoItemInfo(this, "Root", "", "", 30000, null, "7fa159bd-1fe5-4e99-a136-ef9aaecf3d93");
                _validatethistextInfo = new RepoItemInfo(this, "VALIDATETHISTEXT", "?/?/text[@name='VALIDATE THIS TEXT']", "", 30000, null, "ad20b85e-47e3-4f20-8bee-2b204ca62899");
                _submit1Info = new RepoItemInfo(this, "Submit1", "button[@name='Submit']", "", 30000, null, "98186afc-28a9-4645-b1eb-d99745f96e02");
                _none1Info = new RepoItemInfo(this, "None1", "text[@orientation='None']", "", 30000, null, "3bc09b57-cc3a-4045-a331-195a8d5944fe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ed766b88-9f08-48c3-ade0-245c79137dc5")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ed766b88-9f08-48c3-ade0-245c79137dc5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Root item.
            /// </summary>
            [RepositoryItem("7fa159bd-1fe5-4e99-a136-ef9aaecf3d93")]
            public virtual Ranorex.Container Root
            {
                get
                {
                    return _rootInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Root item info.
            /// </summary>
            [RepositoryItemInfo("7fa159bd-1fe5-4e99-a136-ef9aaecf3d93")]
            public virtual RepoItemInfo RootInfo
            {
                get
                {
                    return _rootInfo;
                }
            }

            /// <summary>
            /// The VALIDATETHISTEXT item.
            /// </summary>
            [RepositoryItem("ad20b85e-47e3-4f20-8bee-2b204ca62899")]
            public virtual Ranorex.Text VALIDATETHISTEXT
            {
                get
                {
                    return _validatethistextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The VALIDATETHISTEXT item info.
            /// </summary>
            [RepositoryItemInfo("ad20b85e-47e3-4f20-8bee-2b204ca62899")]
            public virtual RepoItemInfo VALIDATETHISTEXTInfo
            {
                get
                {
                    return _validatethistextInfo;
                }
            }

            /// <summary>
            /// The Submit1 item.
            /// </summary>
            [RepositoryItem("98186afc-28a9-4645-b1eb-d99745f96e02")]
            public virtual Ranorex.Button Submit1
            {
                get
                {
                    return _submit1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Submit1 item info.
            /// </summary>
            [RepositoryItemInfo("98186afc-28a9-4645-b1eb-d99745f96e02")]
            public virtual RepoItemInfo Submit1Info
            {
                get
                {
                    return _submit1Info;
                }
            }

            /// <summary>
            /// The None1 item.
            /// </summary>
            [RepositoryItem("3bc09b57-cc3a-4045-a331-195a8d5944fe")]
            public virtual Ranorex.Text None1
            {
                get
                {
                    return _none1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The None1 item info.
            /// </summary>
            [RepositoryItemInfo("3bc09b57-cc3a-4045-a331-195a8d5944fe")]
            public virtual RepoItemInfo None1Info
            {
                get
                {
                    return _none1Info;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("122b9660-6474-483d-9c38-5b3fdc0f7ca9")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _trayclockwclassInfo;
            RepoItemInfo _microsoftedgeInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "122b9660-6474-483d-9c38-5b3fdc0f7ca9", "")
            {
                _trayclockwclassInfo = new RepoItemInfo(this, "TrayClockWClass", "?/?/text[@class='TrayClockWClass']", "?/?/text[@class='TrayClockWClass']", 30000, null, "2450c906-3f04-469f-acf5-e01bce7fd6c4");
                _microsoftedgeInfo = new RepoItemInfo(this, "MicrosoftEdge", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename='Microsoft Edge']", ".//button[@accessiblename='Microsoft Edge']", 30000, null, "5a960a51-8708-4ba6-b84b-374bed26576b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("122b9660-6474-483d-9c38-5b3fdc0f7ca9")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("122b9660-6474-483d-9c38-5b3fdc0f7ca9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TrayClockWClass item.
            /// </summary>
            [RepositoryItem("2450c906-3f04-469f-acf5-e01bce7fd6c4")]
            public virtual Ranorex.Text TrayClockWClass
            {
                get
                {
                    return _trayclockwclassInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TrayClockWClass item info.
            /// </summary>
            [RepositoryItemInfo("2450c906-3f04-469f-acf5-e01bce7fd6c4")]
            public virtual RepoItemInfo TrayClockWClassInfo
            {
                get
                {
                    return _trayclockwclassInfo;
                }
            }

            /// <summary>
            /// The MicrosoftEdge item.
            /// </summary>
            [RepositoryItem("5a960a51-8708-4ba6-b84b-374bed26576b")]
            public virtual Ranorex.Button MicrosoftEdge
            {
                get
                {
                    return _microsoftedgeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MicrosoftEdge item info.
            /// </summary>
            [RepositoryItemInfo("5a960a51-8708-4ba6-b84b-374bed26576b")]
            public virtual RepoItemInfo MicrosoftEdgeInfo
            {
                get
                {
                    return _microsoftedgeInfo;
                }
            }
        }

        /// <summary>
        /// The NewTabProfile1MicrosoftEdgeAppFolder folder.
        /// </summary>
        [RepositoryFolder("87fa683f-4620-46d2-9ad4-02a3b6457994")]
        public partial class NewTabProfile1MicrosoftEdgeAppFolder : RepoGenBaseFolder
        {
            react_demoRepositoryFolders.NewTabMicrosoftEdgeFolder _newtabmicrosoftedge;
            react_demoRepositoryFolders.RootFolder _root;
            react_demoRepositoryFolders.Root1Folder1 _root1;

            /// <summary>
            /// Creates a new NewTabProfile1MicrosoftEdge  folder.
            /// </summary>
            public NewTabProfile1MicrosoftEdgeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewTabProfile1MicrosoftEdge", "/form[@title>'New tab - Profile 1 - Microsoft​']", parentFolder, 30000, null, true, "87fa683f-4620-46d2-9ad4-02a3b6457994", "")
            {
                _newtabmicrosoftedge = new react_demoRepositoryFolders.NewTabMicrosoftEdgeFolder(this);
                _root = new react_demoRepositoryFolders.RootFolder(this);
                _root1 = new react_demoRepositoryFolders.Root1Folder1(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("87fa683f-4620-46d2-9ad4-02a3b6457994")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("87fa683f-4620-46d2-9ad4-02a3b6457994")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewTabMicrosoftEdge folder.
            /// </summary>
            [RepositoryFolder("0fa6907c-dda1-423c-9388-6b63a00dc600")]
            public virtual react_demoRepositoryFolders.NewTabMicrosoftEdgeFolder NewTabMicrosoftEdge
            {
                get { return _newtabmicrosoftedge; }
            }

            /// <summary>
            /// The Root folder.
            /// </summary>
            [RepositoryFolder("17dc2e86-d21d-448a-919d-56952a025c6d")]
            public virtual react_demoRepositoryFolders.RootFolder Root
            {
                get { return _root; }
            }

            /// <summary>
            /// The Root1 folder.
            /// </summary>
            [RepositoryFolder("f50c1afa-cce7-4030-bca0-0b6d475a1c2b")]
            public virtual react_demoRepositoryFolders.Root1Folder1 Root1
            {
                get { return _root1; }
            }
        }

        /// <summary>
        /// The NewTabMicrosoftEdgeFolder folder.
        /// </summary>
        [RepositoryFolder("0fa6907c-dda1-423c-9388-6b63a00dc600")]
        public partial class NewTabMicrosoftEdgeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somecontainer1Info;
            RepoItemInfo _somecontainerInfo;
            RepoItemInfo _disneyplusInfo;

            /// <summary>
            /// Creates a new NewTabMicrosoftEdge  folder.
            /// </summary>
            public NewTabMicrosoftEdgeFolder(RepoGenBaseFolder parentFolder) :
                    base("NewTabMicrosoftEdge", "container[@name='New tab - Microsoft Edge']", parentFolder, 30000, null, false, "0fa6907c-dda1-423c-9388-6b63a00dc600", "")
            {
                _somecontainer1Info = new RepoItemInfo(this, "SomeContainer1", "container/?/?/container/container", "container/container/container/container", 30000, null, "cab4a33e-12ca-4578-be4e-3064fdbd25ba");
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", "container[2]/?/?/container/container", "container/container", 30000, null, "99594d3f-f158-44f0-bcfc-0f0f94efe085");
                _disneyplusInfo = new RepoItemInfo(this, "DisneyPlus", "container[@name='Microsoft Edge']//container[@automationid='8680832']/?/?/container[@automationid='headerGrid']/container[@automationid='topSitesHolder']/container[@automationid='topSitesCommon']/?/?/container[@automationid='TopSitesCommon']/container[@name='Disney+']", "container[@name='Disney+']", 30000, null, "f14deca0-d4f7-4f6d-beaf-217f45b2dded");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0fa6907c-dda1-423c-9388-6b63a00dc600")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0fa6907c-dda1-423c-9388-6b63a00dc600")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeContainer1 item.
            /// </summary>
            [RepositoryItem("cab4a33e-12ca-4578-be4e-3064fdbd25ba")]
            public virtual Ranorex.Container SomeContainer1
            {
                get
                {
                    return _somecontainer1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer1 item info.
            /// </summary>
            [RepositoryItemInfo("cab4a33e-12ca-4578-be4e-3064fdbd25ba")]
            public virtual RepoItemInfo SomeContainer1Info
            {
                get
                {
                    return _somecontainer1Info;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("99594d3f-f158-44f0-bcfc-0f0f94efe085")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("99594d3f-f158-44f0-bcfc-0f0f94efe085")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }

            /// <summary>
            /// The DisneyPlus item.
            /// </summary>
            [RepositoryItem("f14deca0-d4f7-4f6d-beaf-217f45b2dded")]
            public virtual Ranorex.Container DisneyPlus
            {
                get
                {
                    return _disneyplusInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The DisneyPlus item info.
            /// </summary>
            [RepositoryItemInfo("f14deca0-d4f7-4f6d-beaf-217f45b2dded")]
            public virtual RepoItemInfo DisneyPlusInfo
            {
                get
                {
                    return _disneyplusInfo;
                }
            }
        }

        /// <summary>
        /// The RootFolder folder.
        /// </summary>
        [RepositoryFolder("17dc2e86-d21d-448a-919d-56952a025c6d")]
        public partial class RootFolder : RepoGenBaseFolder
        {
            RepoItemInfo _validatethistextInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _noneInfo;

            /// <summary>
            /// Creates a new Root  folder.
            /// </summary>
            public RootFolder(RepoGenBaseFolder parentFolder) :
                    base("Root", "container[@name>'React App - Microsoft Edg']/container[@name='Microsoft Edge']/?/?/container[@classname='BrowserView']/container[3]//container[@automationid='29469728']/?/?/container[@automationid='root']", parentFolder, 30000, null, false, "17dc2e86-d21d-448a-919d-56952a025c6d", "")
            {
                _validatethistextInfo = new RepoItemInfo(this, "ValidateThisText", "?/?/text[@name='Validate this text']", "", 30000, null, "616115a3-ddc4-4bc3-9f0c-2ca3e39d3636");
                _submitInfo = new RepoItemInfo(this, "Submit", "button[@name='Submit']", "", 30000, null, "a25822d6-466c-4ab8-b56a-6072b8381d82");
                _noneInfo = new RepoItemInfo(this, "None", "text[@orientation='None']", "", 30000, null, "4ff403bc-3880-4368-b888-6de6842c4ec8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("17dc2e86-d21d-448a-919d-56952a025c6d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("17dc2e86-d21d-448a-919d-56952a025c6d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ValidateThisText item.
            /// </summary>
            [RepositoryItem("616115a3-ddc4-4bc3-9f0c-2ca3e39d3636")]
            public virtual Ranorex.Text ValidateThisText
            {
                get
                {
                    return _validatethistextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ValidateThisText item info.
            /// </summary>
            [RepositoryItemInfo("616115a3-ddc4-4bc3-9f0c-2ca3e39d3636")]
            public virtual RepoItemInfo ValidateThisTextInfo
            {
                get
                {
                    return _validatethistextInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("a25822d6-466c-4ab8-b56a-6072b8381d82")]
            public virtual Ranorex.Button Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("a25822d6-466c-4ab8-b56a-6072b8381d82")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("4ff403bc-3880-4368-b888-6de6842c4ec8")]
            public virtual Ranorex.Text None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("4ff403bc-3880-4368-b888-6de6842c4ec8")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }
        }

        /// <summary>
        /// The Root1Folder1 folder.
        /// </summary>
        [RepositoryFolder("f50c1afa-cce7-4030-bca0-0b6d475a1c2b")]
        public partial class Root1Folder1 : RepoGenBaseFolder
        {
            RepoItemInfo _validateInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _inputareaInfo;

            /// <summary>
            /// Creates a new Root1  folder.
            /// </summary>
            public Root1Folder1(RepoGenBaseFolder parentFolder) :
                    base("Root1", "container[@name>'React App - Microsoft Edg']/container[@name='Microsoft Edge']/?/?/container[@classname='BrowserView']/container[3]//container[@automationid='53977248']/?/?/container[@automationid='root']", parentFolder, 30000, null, false, "f50c1afa-cce7-4030-bca0-0b6d475a1c2b", "")
            {
                _validateInfo = new RepoItemInfo(this, "Validate", "?/?/text[@name='validate']", "", 30000, null, "161ed19b-6bce-4da3-bec6-e167ca99027f");
                _submitInfo = new RepoItemInfo(this, "Submit", "button[@name='Submit']", "", 30000, null, "9073c142-7b58-4dd3-b643-cad61a88c44f");
                _inputareaInfo = new RepoItemInfo(this, "InputArea", "text[@automationid='input-area']", "", 30000, null, "c7adb92c-2951-4e9a-8dc7-7aa331e3d7a9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f50c1afa-cce7-4030-bca0-0b6d475a1c2b")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f50c1afa-cce7-4030-bca0-0b6d475a1c2b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Validate item.
            /// </summary>
            [RepositoryItem("161ed19b-6bce-4da3-bec6-e167ca99027f")]
            public virtual Ranorex.Text Validate
            {
                get
                {
                    return _validateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Validate item info.
            /// </summary>
            [RepositoryItemInfo("161ed19b-6bce-4da3-bec6-e167ca99027f")]
            public virtual RepoItemInfo ValidateInfo
            {
                get
                {
                    return _validateInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("9073c142-7b58-4dd3-b643-cad61a88c44f")]
            public virtual Ranorex.Button Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("9073c142-7b58-4dd3-b643-cad61a88c44f")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The InputArea item.
            /// </summary>
            [RepositoryItem("c7adb92c-2951-4e9a-8dc7-7aa331e3d7a9")]
            public virtual Ranorex.Text InputArea
            {
                get
                {
                    return _inputareaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InputArea item info.
            /// </summary>
            [RepositoryItemInfo("c7adb92c-2951-4e9a-8dc7-7aa331e3d7a9")]
            public virtual RepoItemInfo InputAreaInfo
            {
                get
                {
                    return _inputareaInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("c3cc2416-b6ec-4a0f-8cda-9171a52962fb")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _reactappand1morepageprofile1Info;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/form[@title='']", parentFolder, 30000, null, true, "c3cc2416-b6ec-4a0f-8cda-9171a52962fb", "")
            {
                _reactappand1morepageprofile1Info = new RepoItemInfo(this, "ReactAppAnd1MorePageProfile1", "?/?/listitem[@accessiblename>'React App and 1 more page']", "?/?/listitem[@accessiblename>'React App and 1 more page']", 30000, null, "a9cd4678-c822-45ce-968b-e23d24731017");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c3cc2416-b6ec-4a0f-8cda-9171a52962fb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c3cc2416-b6ec-4a0f-8cda-9171a52962fb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ReactAppAnd1MorePageProfile1 item.
            /// </summary>
            [RepositoryItem("a9cd4678-c822-45ce-968b-e23d24731017")]
            public virtual Ranorex.ListItem ReactAppAnd1MorePageProfile1
            {
                get
                {
                    return _reactappand1morepageprofile1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ReactAppAnd1MorePageProfile1 item info.
            /// </summary>
            [RepositoryItemInfo("a9cd4678-c822-45ce-968b-e23d24731017")]
            public virtual RepoItemInfo ReactAppAnd1MorePageProfile1Info
            {
                get
                {
                    return _reactappand1morepageprofile1Info;
                }
            }
        }

        /// <summary>
        /// The ReactAppAnd1MorePageProfile1AppFolder folder.
        /// </summary>
        [RepositoryFolder("712b75b7-9147-44f8-9848-ba634993efa5")]
        public partial class ReactAppAnd1MorePageProfile1AppFolder : RepoGenBaseFolder
        {
            react_demoRepositoryFolders.RootFolder1 _root;
            react_demoRepositoryFolders.Root2Folder1 _root2;

            /// <summary>
            /// Creates a new ReactAppAnd1MorePageProfile1  folder.
            /// </summary>
            public ReactAppAnd1MorePageProfile1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("ReactAppAnd1MorePageProfile1", "/form[@title>'React App and 1 more page']", parentFolder, 30000, null, true, "712b75b7-9147-44f8-9848-ba634993efa5", "")
            {
                _root = new react_demoRepositoryFolders.RootFolder1(this);
                _root2 = new react_demoRepositoryFolders.Root2Folder1(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("712b75b7-9147-44f8-9848-ba634993efa5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("712b75b7-9147-44f8-9848-ba634993efa5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Root folder.
            /// </summary>
            [RepositoryFolder("caabc771-b73d-44c4-85a4-72dbeaf40eff")]
            public virtual react_demoRepositoryFolders.RootFolder1 Root
            {
                get { return _root; }
            }

            /// <summary>
            /// The Root2 folder.
            /// </summary>
            [RepositoryFolder("e683db5d-1f03-4eb1-90af-d0bf456c86fe")]
            public virtual react_demoRepositoryFolders.Root2Folder1 Root2
            {
                get { return _root2; }
            }
        }

        /// <summary>
        /// The RootFolder1 folder.
        /// </summary>
        [RepositoryFolder("caabc771-b73d-44c4-85a4-72dbeaf40eff")]
        public partial class RootFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _validatethistextInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _inputareaInfo;

            /// <summary>
            /// Creates a new Root  folder.
            /// </summary>
            public RootFolder1(RepoGenBaseFolder parentFolder) :
                    base("Root", "container[@name>'React App - Microsoft Edg']/container[@name='Microsoft Edge']/?/?/container[@classname='BrowserView']/container[3]//container[@automationid='24220640']/?/?/container[@automationid='root']", parentFolder, 30000, null, false, "caabc771-b73d-44c4-85a4-72dbeaf40eff", "")
            {
                _validatethistextInfo = new RepoItemInfo(this, "ValidateThisText", "?/?/text[@name='Validate this text']", "", 30000, null, "a79e4e9a-8557-4d82-ace7-ac605d0f9866");
                _submitInfo = new RepoItemInfo(this, "Submit", "button[@name='Submit']", "", 30000, null, "57b3d711-b2a1-4a77-8b90-1ec3cf0060c5");
                _inputareaInfo = new RepoItemInfo(this, "InputArea", "text[@automationid='input-area']", "", 30000, null, "bafb7846-04b3-4b52-b952-0548b7e7b3b5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("caabc771-b73d-44c4-85a4-72dbeaf40eff")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("caabc771-b73d-44c4-85a4-72dbeaf40eff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ValidateThisText item.
            /// </summary>
            [RepositoryItem("a79e4e9a-8557-4d82-ace7-ac605d0f9866")]
            public virtual Ranorex.Text ValidateThisText
            {
                get
                {
                    return _validatethistextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ValidateThisText item info.
            /// </summary>
            [RepositoryItemInfo("a79e4e9a-8557-4d82-ace7-ac605d0f9866")]
            public virtual RepoItemInfo ValidateThisTextInfo
            {
                get
                {
                    return _validatethistextInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("57b3d711-b2a1-4a77-8b90-1ec3cf0060c5")]
            public virtual Ranorex.Button Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("57b3d711-b2a1-4a77-8b90-1ec3cf0060c5")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The InputArea item.
            /// </summary>
            [RepositoryItem("bafb7846-04b3-4b52-b952-0548b7e7b3b5")]
            public virtual Ranorex.Text InputArea
            {
                get
                {
                    return _inputareaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InputArea item info.
            /// </summary>
            [RepositoryItemInfo("bafb7846-04b3-4b52-b952-0548b7e7b3b5")]
            public virtual RepoItemInfo InputAreaInfo
            {
                get
                {
                    return _inputareaInfo;
                }
            }
        }

        /// <summary>
        /// The Root2Folder1 folder.
        /// </summary>
        [RepositoryFolder("e683db5d-1f03-4eb1-90af-d0bf456c86fe")]
        public partial class Root2Folder1 : RepoGenBaseFolder
        {
            RepoItemInfo _root1Info;
            RepoItemInfo _validatethistextInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _inputareaInfo;

            /// <summary>
            /// Creates a new Root2  folder.
            /// </summary>
            public Root2Folder1(RepoGenBaseFolder parentFolder) :
                    base("Root2", "container[@name>'React App - Microsoft Edg']/container[@name='Microsoft Edge']/?/?/container[@classname='BrowserView']/container[3]//container[@automationid='27064064']/?/?/container[@automationid='root']", parentFolder, 30000, null, false, "e683db5d-1f03-4eb1-90af-d0bf456c86fe", "")
            {
                _root1Info = new RepoItemInfo(this, "Root1", "", "", 30000, null, "41decd44-755f-4dba-8d6e-295e3f1d5bdd");
                _validatethistextInfo = new RepoItemInfo(this, "ValidateThisText", "?/?/text[@name='validate this text']", "", 30000, null, "c4574601-6800-41f0-81ec-8df1ff45ad43");
                _submitInfo = new RepoItemInfo(this, "Submit", "button[@name='Submit']", "", 30000, null, "116931cb-713f-4e44-b5ab-b2b4c648ba0d");
                _inputareaInfo = new RepoItemInfo(this, "InputArea", "text[@automationid='input-area']", "", 30000, null, "0660f389-dc6d-4d94-bdfa-381e8e72c028");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e683db5d-1f03-4eb1-90af-d0bf456c86fe")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e683db5d-1f03-4eb1-90af-d0bf456c86fe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Root1 item.
            /// </summary>
            [RepositoryItem("41decd44-755f-4dba-8d6e-295e3f1d5bdd")]
            public virtual Ranorex.Container Root1
            {
                get
                {
                    return _root1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Root1 item info.
            /// </summary>
            [RepositoryItemInfo("41decd44-755f-4dba-8d6e-295e3f1d5bdd")]
            public virtual RepoItemInfo Root1Info
            {
                get
                {
                    return _root1Info;
                }
            }

            /// <summary>
            /// The ValidateThisText item.
            /// </summary>
            [RepositoryItem("c4574601-6800-41f0-81ec-8df1ff45ad43")]
            public virtual Ranorex.Text ValidateThisText
            {
                get
                {
                    return _validatethistextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ValidateThisText item info.
            /// </summary>
            [RepositoryItemInfo("c4574601-6800-41f0-81ec-8df1ff45ad43")]
            public virtual RepoItemInfo ValidateThisTextInfo
            {
                get
                {
                    return _validatethistextInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("116931cb-713f-4e44-b5ab-b2b4c648ba0d")]
            public virtual Ranorex.Button Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("116931cb-713f-4e44-b5ab-b2b4c648ba0d")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The InputArea item.
            /// </summary>
            [RepositoryItem("0660f389-dc6d-4d94-bdfa-381e8e72c028")]
            public virtual Ranorex.Text InputArea
            {
                get
                {
                    return _inputareaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InputArea item info.
            /// </summary>
            [RepositoryItemInfo("0660f389-dc6d-4d94-bdfa-381e8e72c028")]
            public virtual RepoItemInfo InputAreaInfo
            {
                get
                {
                    return _inputareaInfo;
                }
            }
        }

        /// <summary>
        /// The ReactAppAppFolder folder.
        /// </summary>
        [RepositoryFolder("b542ea33-a686-4ec5-95ec-85115e3453e3")]
        public partial class ReactAppAppFolder : RepoGenBaseFolder
        {
            react_demoRepositoryFolders.ContainerFolder _container;

            /// <summary>
            /// Creates a new ReactApp  folder.
            /// </summary>
            public ReactAppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ReactApp", "/dom[@domain='localhost:3000']", parentFolder, 30000, null, false, "b542ea33-a686-4ec5-95ec-85115e3453e3", "")
            {
                _container = new react_demoRepositoryFolders.ContainerFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b542ea33-a686-4ec5-95ec-85115e3453e3")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b542ea33-a686-4ec5-95ec-85115e3453e3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Container folder.
            /// </summary>
            [RepositoryFolder("2cdd7e3e-d646-4312-94a7-b7586695d551")]
            public virtual react_demoRepositoryFolders.ContainerFolder Container
            {
                get { return _container; }
            }
        }

        /// <summary>
        /// The ContainerFolder folder.
        /// </summary>
        [RepositoryFolder("2cdd7e3e-d646-4312-94a7-b7586695d551")]
        public partial class ContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _subcontainerInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _enteringtextforvalidationInfo;

            /// <summary>
            /// Creates a new Container  folder.
            /// </summary>
            public ContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("Container", ".//div[#'root']/div/div", parentFolder, 30000, null, false, "2cdd7e3e-d646-4312-94a7-b7586695d551", "")
            {
                _subcontainerInfo = new RepoItemInfo(this, "SubContainer", "div[1]", "div[1]", 30000, null, "a79be58c-856d-42b2-afd4-e765255d7bed");
                _submitInfo = new RepoItemInfo(this, "Submit", "div[1]/button[@innertext='Submit']", "", 30000, null, "c1a36e3c-67e3-419e-935f-461235c3569e");
                _enteringtextforvalidationInfo = new RepoItemInfo(this, "EnteringTextForValidation", "div[2]/p[@innertext>'entering text for validat']", "", 30000, null, "8badb41a-1f1a-4e42-b0d0-537790b21950");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2cdd7e3e-d646-4312-94a7-b7586695d551")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2cdd7e3e-d646-4312-94a7-b7586695d551")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SubContainer item.
            /// </summary>
            [RepositoryItem("a79be58c-856d-42b2-afd4-e765255d7bed")]
            public virtual Ranorex.DivTag SubContainer
            {
                get
                {
                    return _subcontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SubContainer item info.
            /// </summary>
            [RepositoryItemInfo("a79be58c-856d-42b2-afd4-e765255d7bed")]
            public virtual RepoItemInfo SubContainerInfo
            {
                get
                {
                    return _subcontainerInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("c1a36e3c-67e3-419e-935f-461235c3569e")]
            public virtual Ranorex.ButtonTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("c1a36e3c-67e3-419e-935f-461235c3569e")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The EnteringTextForValidation item.
            /// </summary>
            [RepositoryItem("8badb41a-1f1a-4e42-b0d0-537790b21950")]
            public virtual Ranorex.PTag EnteringTextForValidation
            {
                get
                {
                    return _enteringtextforvalidationInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The EnteringTextForValidation item info.
            /// </summary>
            [RepositoryItemInfo("8badb41a-1f1a-4e42-b0d0-537790b21950")]
            public virtual RepoItemInfo EnteringTextForValidationInfo
            {
                get
                {
                    return _enteringtextforvalidationInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
